-- AlterEnum
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'ONAYLANDI';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'EXPENSE_MARKED';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'CLIENT_CALL_UPDATED';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'SEND_QUEUED';

-- CreateEnum
DO $$ BEGIN
  CREATE TYPE "ClientCallStatus" AS ENUM ('YOK', 'ARANACAK', 'YAPILDI');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- AlterTable
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "expensePaid" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "expensePaidAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "clientCallStatus" "ClientCallStatus" NOT NULL DEFAULT 'YOK';
