-- Enums
ALTER TYPE "TaskStatus" ADD VALUE IF NOT EXISTS 'KONTROL_EDILECEK';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'MOVED_TO_CHECK';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'COMPLETED_DIRECT';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'SOFT_DELETED';
ALTER TYPE "LogType" ADD VALUE IF NOT EXISTS 'RESTORED';

-- User drive link
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "driveFolderLink" TEXT;

-- Soft delete columns
ALTER TABLE "Client" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "CaseFile" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Task" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Client_deletedAt_idx" ON "Client"("deletedAt");
CREATE INDEX IF NOT EXISTS "CaseFile_deletedAt_idx" ON "CaseFile"("deletedAt");
CREATE INDEX IF NOT EXISTS "Task_deletedAt_idx" ON "Task"("deletedAt");
